fixes

diff --git a/tools/hedgehog/DDL_updates/000010_ddl_tlds.in b/tools/hedgehog/DDL_updates/000010_ddl_tlds.in
--- a/tools/hedgehog/DDL_updates/000010_ddl_tlds.in
+++ b/tools/hedgehog/DDL_updates/000010_ddl_tlds.in
@@ -1,15 +1,85 @@
-create table tld_types (id serial primary key,
-                        type_name text);
+#!/bin/bash
+#
+# Copyright 2015 Internet Corporation for Assigned Names and Numbers.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+# 
+# http://www.apache.org/licenses/LICENSE-2.0
+# 
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
 
+#
+# Developed by Sinodun IT (www.sinodun.com)
+#
+
+# 
+# File:   000010_ddl_tlds
+#
+
+eval $(@LIBEXEC@/conf_read)
+
+DB_NAME=$hhconfig_database_name
+DATA_DIR=$hhconfig_directories_data
+SQ="'"
+export PGPASSWORD=$hhconfig_database_owner_pass
+
+set -e
+NEW_DDL_SERIAL=10
+REQUIRED_DDL_SERIAL=$(( $NEW_DDL_SERIAL - 1 ))
+NEW_API_VERSION=8
+REQUIRED_API_VERSION=$(( $NEW_API_VERSION - 1 ))
+
+DSC_SCHEMA="dsc"
+
+usage () {
+    echo
+    echo "Usage: $(basename $0) options"
+    echo
+    echo "Supported options:"
+    echo "  -h Show this help."
+    exit 1
+}
+
+
+while getopts ":csh" opt; do
+    case $opt in
+        h  ) usage ;;
+        \? ) usage ;;
+    esac
+done
+
+echo "`date`: $0 COMMENCED"
+USER=$(whoami)
+[ $USER != $hhconfig_database_owner ] && echo "Must be $hhconfig_database_owner to run this script" && exit 1
+
+DB_API_VERSION=`psql -h $hhconfig_database_host $DB_NAME -tc  "select version from dsc.version;"`
+[ $DB_API_VERSION != $REQUIRED_API_VERSION ] && echo "Error: Database API version incorrect." && exit 1
+
+LAST_SERIAL=`psql -h $hhconfig_database_host $DB_NAME -tc  "select max(serial) from dsc.internal_version;"`
+[ $LAST_SERIAL != $REQUIRED_DDL_SERIAL ] && echo "Error: ddl scripts not run in correct order." && exit 1
+
+psql -h $hhconfig_database_host $DB_NAME <<EOF
+BEGIN;
+create table tld_types (id serial primary key, type_name text);
 insert into tld_types (type_name) values
   ('New-gTLD'),
-  ('Legaacy-gTLD'),
+  ('Legacy-gTLD'),
   ('ccTLD');
-  
 create table tlds (id serial primary key,
                    alabel text,
-                   ulabel text
-                   english text
-                   type int REFERENCES tld_types (id);
+                   ulabel text,
+                   english text,
+                   type int REFERENCES tld_types (id));
+UPDATE $DSC_SCHEMA.version SET version = $NEW_API_VERSION;
+INSERT INTO $DSC_SCHEMA.internal_version ( serial, script, description, applied ) VALUES ( $NEW_DDL_SERIAL, '$0', 'Added new query/response difference plot for rssac', now() );
+COMMIT;
+EOF
 
-#insert into tlds (alabel, ulabel, english) values
+echo "`date`: $0 COMPLETED"
