Improve date checking in the tools scripts

diff --git a/tools/hedgehog_plotcache_generate_cached_plots.sh.in b/tools/hedgehog_plotcache_generate_cached_plots.sh.in
--- a/tools/hedgehog_plotcache_generate_cached_plots.sh.in
+++ b/tools/hedgehog_plotcache_generate_cached_plots.sh.in
@@ -66,18 +66,26 @@ echo "`date`: $0 COMMENCED"
 [ $USER != $hhconfig_database_owner ] && echo "Must be $hhconfig_database_owner to run this script" && exit 1
 
 # Validate the start date
-date "+%Y-%m-%dT%H:%M" -d ${FROM} >/dev/null 2>&1
+if [[ ! $FROM =~ ^[0-9]{4}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]$ ]] ; then
+		echo "Error: The start date is not in the required format of YYYY-MM-DDThh:mm" 
+		exit 1
+fi
+date "+%Y-%m-%dT%H:%M" --date="${FROM}" >/dev/null 2>&1
 is_valid=$?
 if [ ${is_valid} -ne 0 ] ; then
-	echo "Error: The start date is not in the required format of YYYY-MM-DDThh:mm" 
+	echo "Error: The start date is invalid" 
 	exit 1
 fi
 
 # Validate the end date
-date "+%Y-%m-%dT%H:%M" -d ${TO} >/dev/null 2>&1
+if [[ ! $TO =~ ^[0-9]{4}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]$ ]] ; then
+		echo "Error: The end date is not in the required format of YYYY-MM-DDThh:mm" 
+		exit 1
+fi
+date "+%Y-%m-%dT%H:%M" --date="${TO}" >/dev/null 2>&1
 is_valid=$?
 if [ ${is_valid} -ne 0 ] ; then
-	echo "Error: The end date is not in the required format of YYYY-MM-DDThh:mm" 
+	echo "Error: The end date is invalid" 
 	exit 1
 fi
 
diff --git a/tools/hedgehog_rssac_rm_old_unique_source_data.sh.in b/tools/hedgehog_rssac_rm_old_unique_source_data.sh.in
--- a/tools/hedgehog_rssac_rm_old_unique_source_data.sh.in
+++ b/tools/hedgehog_rssac_rm_old_unique_source_data.sh.in
@@ -76,16 +76,19 @@ DB_API_VERSION=`psql $DB_NAME -tc  "select version from dsc.version;"`
 
 # Validate the input date. Add day since (oddly) date won't parse just year and month
 if [ ! -z $START ] ; then
-	date "+%Y-%m-%d" -d ${START}-01 >/dev/null 2>&1
+	if [[ ! $START =~ ^[0-9]{4}-[0-1][0-9]$ ]] ; then
+			echo "Error: The start date is not in the required format of YYYY-MM" 
+			exit 1
+	fi
+	date "+%Y-%m-%d" --date="${START}-01" >/dev/null 2>&1
 	is_valid=$?
 	if [ ${is_valid} -ne 0 ] ; then
-		echo "Error: The start date is not in the required format of YYYY-MM" 
+		echo "Error: The start date is not valid" 
 		exit 1
 	fi
 	
 	START_FIRST=`date --date=$START-01 +%Y%m%d`
 	NOW_FIRST=`date --date="$NOW" +%Y%m01`
-	echo  $NOW_FIRST $START_FIRST
 	if [ $NOW_FIRST -le $START_FIRST ] ; then
 		echo "Error: The given month cannot be this month or in the future." 
 		exit 1
