Minor fixups to refile_and_grok.sh

diff --git a/tools/refile_and_grok.sh.in b/tools/refile_and_grok.sh.in
--- a/tools/refile_and_grok.sh.in
+++ b/tools/refile_and_grok.sh.in
@@ -38,6 +38,7 @@ RESERVED_CPUS=0
 DB_NAME="$hhconfig_database_name"
 ARGS=""
 LOG="dsc-extractor.out"
+APPEND_LOG=0
 REQUIRED_API_VERSION=DB_VERSION
 
 usage () {
@@ -50,12 +51,13 @@ usage () {
     echo "-s Start date from which to process incoming data (XML input only)"
     echo "-r Disable processing of rssac data. Default is to process all data."
     echo "-R Reserved processors. Number of CPUS processors to exclude from import (default 0)."
+    echo "-a Append output to the $PROG.stdout file (default is overwrite)"
     echo "-h Show this help."
     echo
 }
 
 
-while getopts ":w:i:o:cs:rR:h" opt; do
+while getopts ":w:i:o:cs:raR:h" opt; do
     case "$opt" in
         w  ) WD=$OPTARG ;;
         i  ) INPUT=$OPTARG ;;
@@ -64,6 +66,7 @@ while getopts ":w:i:o:cs:rR:h" opt; do
         r  ) RSSAC_FLAG="-r" ;;
         R  ) RESERVED_CPUS=$OPTARG ;;
         c  ) CRON=1 ;;
+        a  ) APPEND_LOG=1 ;;
         h  ) usage
              exit 1 ;;
         \? ) usage
@@ -74,7 +77,7 @@ done
 [ "$USER" != "$hhconfig_database_owner" ] && echo "Must be $hhconfig_database_owner to run this script." && exit 1
 
 DB_API_VERSION=$(psql "$DB_NAME"  -tc  "select version from dsc.version;")
-[ "$DB_API_VERSION" != "$REQUIRED_API_VERSION" ] && echo "Error: Database API version incorrect." && exit 1
+[ "$DB_API_VERSION" -ne "$REQUIRED_API_VERSION" ] && echo "Error: Database API version incorrect. Current version is $DB_API_VERSION, required version is $REQUIRED_API_VERSION" && exit 1
 
 if ! [[ "$RESERVED_CPUS" =~ ^[0-9]+$ ]] ; then
 	echo "Reserved CPUS ($RESERVED_CPUS) is not a positive number. Exiting."
@@ -105,13 +108,17 @@ then
     echo "LOG = $LOG"
     echo -n "Would you like to continue? y/N: "
     read c
-    [[ "$c" =~ ^(Y|y) ]] && exit 1
+    [[ ! "$c" =~ ^(Y|y) ]] && exit 1
 fi
 
 #set -x #Print commands just before execution - with all expansions and substitutions done, and words marked - useful for debugging.
 
 cd "${WD}"
-exec >"$PROG.stdout"
+if [ $APPEND_LOG -eq 1 ]; then
+	exec >>"$PROG.stdout"
+else 
+	exec >"$PROG.stdout"
+fi
 #exec 2>&1
 
 echo "$(date) SCRIPT COMMENCED"
