more

diff --git a/tools/hedgehog/check_user_perms.in b/tools/hedgehog/check_user_perms.in
--- a/tools/hedgehog/check_user_perms.in
+++ b/tools/hedgehog/check_user_perms.in
@@ -45,10 +45,12 @@ usage () {
   echo
   echo "Supported options:"
   echo "  -C <API_VERSION> specify DB API version to check for (implies -c)"
+  echo "  -n Indicate that the user doesn't need to access the database"
   echo "  -s <SERIAL_NUMBER> check DB serial number"
   echo "  -c check databse API version against the build time API version"
   echo "  -f check user has write permission to $hhconfig_directories_data"
   echo "  -g check user has write permission to web directory ${hhconfig_directories_rssac%rssac}"
+  echo "  -p check user has write permission to plotcache directory $hhconfig_directories_plotcache"
   echo "  -w check we are a write user of the DB"
   echo "  -U specify a DB user"
   echo "  -P specify a DB password"
@@ -62,19 +64,24 @@ CHECK_API=0
 CHECK_SERIAL=0
 CHECK_DATA_DIR=0
 CHECK_RSSAC_DIR=0
+CHECK_PLOT_CACHE_DIR=0
 SPECIFIED_PASS=""
 SPECIFIED_USER=""
+# By default check for a database connection
+CHECK_DB_CONN=1
 
 REQUIRED_API_VERSION=@DB_VERSION@
 
-while getopts ":C:cdfgP:s:U:whv" opt; do
+while getopts ":C:ncdfgpP:s:U:whv" opt; do
     case $opt in
     C  ) REQUIRED_API_VERSION=$OPTARG
          CHECK_API=1 ;;
+    n  ) CHECK_DB_CONN=0 ;;
     c  ) CHECK_API=1 ;;
     d  ) set -x ;;
     f  ) CHECK_DATA_DIR=1 ;;
     g  ) CHECK_RSSAC_DIR=1 ;;
+    p  ) CHECK_PLOT_CACHE_DIR=1 ;;
     P  ) SPECIFIED_PASS=$OPTARG ;;
     s  ) CHECK_SERIAL=1
          REQUIRED_DDL_SERIAL=$OPTARG ;;
@@ -88,73 +95,75 @@ while getopts ":C:cdfgP:s:U:whv" opt; do
          exit 1 ;;
     esac
 done
+if [ $CHECK_DB_CONN -eq 1 ] ; then
 
-USER_NAME=$hhconfig_database_read_user
-if [ -z $USER_NAME ]; then
-  echo "Database user name not set"
-  exit 1
-fi
-export PGPASSWORD="$hhconfig_database_read_pass"
-if [ $WRITER -eq 1 ] ; then
-  USER_NAME=$hhconfig_database_owner
-  export PGPASSWORD="$hhconfig_database_owner_pass"
-fi
-if [ -n "$SPECIFIED_USER" ] ; then
-  USER_NAME=$SPECIFIED_USER
-  export PGPASSWORD="$SPECIFIED_PASS"
-fi
-
-# If the password is set then assume md5 authentication otherwise you must be
-# a user with the same name as the hedgehog database owner and are using peer
-# authentication
-if [ -z "$PGPASSWORD" ] ; then
-  USER=$(whoami)
-  if [ "$USER" != "$USER_NAME" ] ; then
-    echo "Must be user: $USER_NAME and using peer authentication to run this script"
+  USER_NAME=$hhconfig_database_read_user
+  if [ -z $USER_NAME ]; then
+    echo "Database user name not set"
     exit 1
   fi
-fi
+  export PGPASSWORD="$hhconfig_database_read_pass"
+  if [ $WRITER -eq 1 ] ; then
+    USER_NAME=$hhconfig_database_owner
+    export PGPASSWORD="$hhconfig_database_owner_pass"
+  fi
+  if [ -n "$SPECIFIED_USER" ] ; then
+    USER_NAME=$SPECIFIED_USER
+    export PGPASSWORD="$SPECIFIED_PASS"
+  fi
 
-PORT=$hhconfig_database_port
-if [ -z $PORT ] ; then
-  PORT=5432
-fi
-DB_NAME=$hhconfig_database_name
-if [ -z $DB_NAME ] ; then
-  echo "Database name not set"
-  exit 1
-fi
-DB_HOST=$hhconfig_database_host
-if [ -z $DB_HOST ]; then
-  echo "Database host not set"
-  exit 1
-fi
-
-CONN_STRING="-h $DB_HOST -U $USER_NAME -p $PORT -d $DB_NAME"
-# Test connection to the database
-psql $CONN_STRING -tc "\conninfo" > /dev/null
-if [ $? -ne 0 ] ; then
-  echo "Error connecting to database using connection string $CONN_STRING"
-  exit 1
-fi
-
-# Now test the optional parameters...
-TEST=$(psql $CONN_STRING -tc "SELECT has_table_privilege('dsc.version', 'SELECT')" | tr -d '[:space:]')
-if [ $WRITER -eq 1 ] ; then
-  TEST=$(psql $CONN_STRING -tc "SELECT has_table_privilege('dsc.version', 'INSERT')" | tr -d '[:space:]')
-fi
-
-if [ "x$TEST" == "xt" ] ; then
-  if [ $CHECK_API -eq 1 ] ; then
-    DB_API_VERSION=$(psql $CONN_STRING -tc  "select version from dsc.version;")
-    if [ $DB_API_VERSION -ne $REQUIRED_API_VERSION ] ; then
-      echo "Error: Database API version incorrect: Found $DB_API_VERSION expected $REQUIRED_API_VERSION"
+  # If the password is set then assume md5 authentication otherwise you must be
+  # a user with the same name as the hedgehog database owner and are using peer
+  # authentication
+  if [ -z "$PGPASSWORD" ] ; then
+    USER=$(whoami)
+    if [ "$USER" != "$USER_NAME" ] ; then
+      echo "Must be user: $USER_NAME and using peer authentication to run this script"
       exit 1
     fi
   fi
-else
-  echo "The user $USER_NAME does not have the expected database access."
-  exit 1
+
+  PORT=$hhconfig_database_port
+  if [ -z $PORT ] ; then
+    PORT=5432
+  fi
+  DB_NAME=$hhconfig_database_name
+  if [ -z $DB_NAME ] ; then
+    echo "Database name not set"
+    exit 1
+  fi
+  DB_HOST=$hhconfig_database_host
+  if [ -z $DB_HOST ]; then
+    echo "Database host not set"
+    exit 1
+  fi
+
+  CONN_STRING="-h $DB_HOST -U $USER_NAME -p $PORT -d $DB_NAME"
+  # Test connection to the database
+  psql $CONN_STRING -tc "\conninfo" > /dev/null
+  if [ $? -ne 0 ] ; then
+    echo "Error connecting to database using connection string $CONN_STRING"
+    exit 1
+  fi
+
+  # Now test the optional parameters...
+  TEST=$(psql $CONN_STRING -tc "SELECT has_table_privilege('dsc.version', 'SELECT')" | tr -d '[:space:]')
+  if [ $WRITER -eq 1 ] ; then
+    TEST=$(psql $CONN_STRING -tc "SELECT has_table_privilege('dsc.version', 'INSERT')" | tr -d '[:space:]')
+  fi
+
+  if [ "x$TEST" == "xt" ] ; then
+    if [ $CHECK_API -eq 1 ] ; then
+      DB_API_VERSION=$(psql $CONN_STRING -tc  "select version from dsc.version;")
+      if [ $DB_API_VERSION -ne $REQUIRED_API_VERSION ] ; then
+        echo "Error: Database API version incorrect: Found $DB_API_VERSION expected $REQUIRED_API_VERSION"
+        exit 1
+      fi
+    fi
+  else
+    echo "The user $USER_NAME does not have the expected database access."
+    exit 1
+  fi
 fi
 
 if [ $CHECK_SERIAL -eq 1 ] ; then
@@ -183,7 +192,18 @@ if [ $CHECK_RSSAC_DIR -eq 1 ] ; then
   fi
 fi
 
+if [ $CHECK_PLOT_CACHE_DIR -eq 1 ] ; then
+  DATA_OWNER=$(stat -c %U $hhconfig_directories_plotcache)
+  if [ "$DATA_OWNER" != "$USER" ] ; then
+    echo "The user $USER  does not have write access to the plotcache dirctory $hhconfig_directories_plotcache"
+    exit 1
+  fi
+fi
+
 # print env variables for eval to process in calling script
+echo "CONF_DIR=\"$hhconfig_directories_conf\""
+echo "PLOT_CACHE_DIR=\"$hhconfig_directories_plotcache\""
+echo "DATADIR=\"$hhconfig_directories_data\""
 echo "PGPASSWORD=\"$PGPASSWORD\""
 echo "CONN_STRING=\"$CONN_STRING\""
 exit 0
