continued work on ip2asn

diff --git a/tools/hedgehog/check_user_db_api.in b/tools/hedgehog/check_user_db_api.in
--- a/tools/hedgehog/check_user_db_api.in
+++ b/tools/hedgehog/check_user_db_api.in
@@ -50,6 +50,8 @@ usage () {
 	echo "  -d run in debug mode."
 	echo "  -f check user has write permission to $hhconfig_directories_data"
 	echo "  -g check user has write permission to $hhconfig_directories_rssac"
+	echo "  -P specify a password"
+	echo "  -U specify a user"
 	echo "  -w check we are a write user"
     echo "  -h Show this help."
 }
@@ -59,10 +61,12 @@ WRITER=0
 CHECK_API=0
 CHECK_DATA_DIR=0
 CHECK_RSSAC_DIR=0
+SPECIFIED_PASS=""
+SPECIFIED_USER=""
 
 REQUIRED_API_VERSION=@DB_VERSION@
 
-while getopts ":C:cdfgw" opt; do
+while getopts ":C:cdfgP:U:wh" opt; do
     case $opt in
 		C  ) REQUIRED_API_VERSION=$OPTARG
 		     CHECK_API=1 ;;
@@ -70,6 +74,8 @@ while getopts ":C:cdfgw" opt; do
 		d  ) set -x ;;
 		f  ) CHECK_DATA_DIR=1 ;;
 		g  ) CHECK_RSSAC_DIR=1 ;;
+		P  ) SPECIFIED_PASS=$OPTARG ;;
+		U  ) SPECIFIED_USER=$OPTARG ;;
 		w  ) WRITER=1 ;;
         h  ) usage
              exit 1 ;;
@@ -88,14 +94,18 @@ if [ $WRITER -eq 1 ] ; then
 	USER_NAME=$hhconfig_database_owner
 	export PGPASSWORD="$hhconfig_database_owner_pass"
 fi
+if [ -n "$SPECIFIED_USER" ] ; then
+	USER_NAME=$SPECIFIED_USER
+	export PGPASSWORD="$SPECIFIED_PASS"
+fi
 
 # If the password is set then assume md5 authentication otherwise you must be
 # a user with the same name as the hedgehog database owner and are using peer
 # authentication
-if [ -z $PGPASSWORD ] ; then
+if [ -z "$PGPASSWORD" ] ; then
 	USER=$(whoami)
-	if [ $USER != $USER_NAME ] ; then
-		echo "Must be $USER_NAME to run this script"
+	if [ "$USER" != "$USER_NAME" ] ; then
+		echo "Must be $USER_NAME and using peer authentication to run this script"
 		exit 1
 	fi
 fi
@@ -117,9 +127,15 @@ fi
 
 CONN_STRING="-h $DB_HOST -U $USER_NAME -p $PORT -d $DB_NAME"
 # Test connection to the database
-TEST=$(psql $CONN_STRING -tc "SELECT has_table_privilege('version', 'SELECT')" | tr -d '[:space:]')
+psql $CONN_STRING -tc "\conninfo" > /dev/null
+if [ $? -ne 0 ] ; then
+	echo "Error connecting to database using connection string $CONN_STRING"
+	exit 1
+fi
+
+TEST=$(psql $CONN_STRING -tc "SELECT has_table_privilege('dsc.version', 'SELECT')" | tr -d '[:space:]')
 if [ $WRITER -eq 1 ] ; then
-	TEST=$(psql $CONN_STRING -tc "SELECT has_table_privilege('version', 'INSERT')" | tr -d '[:space:]')
+	TEST=$(psql $CONN_STRING -tc "SELECT has_table_privilege('dsc.version', 'INSERT')" | tr -d '[:space:]')
 fi
 
 if [ "x$TEST" == "xt" ] ; then
